name = "GWBackFinder"
uuid = "7fa44c00-b40e-49bf-9bf3-4f6997ab6254"
authors = ["Androniki Dimitriou"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
